### ISSUE TITLE
wnck-applet crashes randomly since update to 1.26

### ISSUE THREAD

**Issue by g550** [mate-desktop/mate-panel#1246]
#### Expected behaviour

Using wnck-applet without sudden crashes

#### Actual behaviour

wnck-applet crashes and a dialogue appears that suggests to reload it

Here's a representative stack trace:

    Aug 26 14:30:26 bebox systemd-coredump[75897]: [🡕] Process 75478 (wnck-applet) of user 1000 dumped core.
                                                   
                                                   Stack trace of thread 75478:
                                                   #0  0x00007f680ab8a6ce n/a (libgdk-3.so.0 + 0x7e6ce)
                                                   #1  0x00007f680ab3e61c gdk_device_get_window_at_position_double (libgdk-3.so.0 + 0x3261c)
                                                   #2  0x00007f680ab3e73e gdk_device_get_window_at_position (libgdk-3.so.0 + 0x3273e)
                                                   #3  0x00007f680aef80e2 gtk_tooltip_trigger_tooltip_query (libgtk-3.so.0 + 0x2ed0e2)
                                                   #4  0x00007f680a69fb08 g_slist_foreach (libglib-2.0.so.0 + 0x6fb08)
                                                   #5  0x00007f680af40c7a n/a (libgtk-3.so.0 + 0x335c7a)
                                                   #6  0x00007f680ab3a85c n/a (libgdk-3.so.0 + 0x2e85c)
                                                   #7  0x00007f680a684015 g_main_context_dispatch (libglib-2.0.so.0 + 0x54015)
                                                   #8  0x00007f680a6d7b99 n/a (libglib-2.0.so.0 + 0xa7b99)
                                                   #9  0x00007f680a683693 g_main_loop_run (libglib-2.0.so.0 + 0x53693)
                                                   #10 0x00007f680ade085f gtk_main (libgtk-3.so.0 + 0x1d585f)
                                                   #11 0x00007f680b454c1b n/a (libmate-panel-applet-4.so.1 + 0x7c1b)
                                                   #12 0x00005616b4ecc15a n/a (wnck-applet + 0x715a)
                                                   #13 0x00007f680a477b25 __libc_start_main (libc.so.6 + 0x27b25)
                                                   #14 0x00005616b4ecc1be n/a (wnck-applet + 0x71be)
                                                   
                                                   Stack trace of thread 75480:
                                                   #0  0x00007f680a543b2f __poll (libc.so.6 + 0xf3b2f)
                                                   #1  0x00007f680a6d7b29 n/a (libglib-2.0.so.0 + 0xa7b29)
                                                   #2  0x00007f680a683693 g_main_loop_run (libglib-2.0.so.0 + 0x53693)
                                                   #3  0x00007f680a8c08c8 n/a (libgio-2.0.so.0 + 0x1018c8)
                                                   #4  0x00007f680a6b22c1 n/a (libglib-2.0.so.0 + 0x822c1)
                                                   #5  0x00007f6809d32259 start_thread (libpthread.so.0 + 0x9259)
                                                   #6  0x00007f680a54e5e3 __clone (libc.so.6 + 0xfe5e3)
                                                   
                                                   Stack trace of thread 75479:
                                                   #0  0x00007f680a543b2f __poll (libc.so.6 + 0xf3b2f)
                                                   #1  0x00007f680a6d7b29 n/a (libglib-2.0.so.0 + 0xa7b29)
                                                   #2  0x00007f680a681871 g_main_context_iteration (libglib-2.0.so.0 + 0x51871)
                                                   #3  0x00007f680a6818c2 n/a (libglib-2.0.so.0 + 0x518c2)
                                                   #4  0x00007f680a6b22c1 n/a (libglib-2.0.so.0 + 0x822c1)
                                                   #5  0x00007f6809d32259 start_thread (libpthread.so.0 + 0x9259)
                                                   #6  0x00007f680a54e5e3 __clone (libc.so.6 + 0xfe5e3)
                                                   
                                                   Stack trace of thread 75487:
                                                   #0  0x00007f680a543b2f __poll (libc.so.6 + 0xf3b2f)
                                                   #1  0x00007f680a6d7b29 n/a (libglib-2.0.so.0 + 0xa7b29)
                                                   #2  0x00007f680a681871 g_main_context_iteration (libglib-2.0.so.0 + 0x51871)
                                                   #3  0x00007f68040abebe n/a (libdconfsettings.so + 0x5ebe)
                                                   #4  0x00007f680a6b22c1 n/a (libglib-2.0.so.0 + 0x822c1)
                                                   #5  0x00007f6809d32259 start_thread (libpthread.so.0 + 0x9259)
                                                   #6  0x00007f680a54e5e3 __clone (libc.so.6 + 0xfe5e3)

#### Steps to reproduce the behaviour

This occurs intermittetly, but has only started once Manjaro delivered the updates to 1.26. It's hard to say what triggers it exactly, but opening or closing windows, opening and closing tabs in a browser as well as changing the focus of windows have all triggered it sometimes.

#### MATE general version

1.26.0

#### Package version

mate-panel 1.26.0-1
libwnck3 40.0-1

#### Linux Distribution

Manjaro

#### Link to bugreport of your Distribution (requirement)

Since the Mate packages for Manjaro are taken downstream from Arch, I reported it there:

https://bugs.archlinux.org/task/71926

**Comment by diegosardina** [comment]
Same problem here on Gentoo, I can't debug it because of cflags

**Comment by mbkma** [comment]
can you reproduce this with current master branch? I.e. does https://github.com/mate-desktop/mate-panel/commit/0a5006eba63a8214e6448b491b22663d0c13e54e fix the problem?

**Comment by diegosardina** [comment]
Ok, I applied that patch and compiled it with CFLAGS="-O1 -Wall -g -pipe -ggdb".
Let's see what is going to happen.

> You could try to launch mate-panel in gdb and report the backtrace here.

Sorry for the noob question: there is a way to prevent mate to re-run mate-panel after killing it?

**Comment by mbkma** [comment]
Sorry I forgot to mention that you will need https://github.com/mate-desktop/mate-panel/commit/0a5006eba63a8214e6448b491b22663d0c13e54e as well.

> Sorry for the noob question: there is a way to prevent mate to re-run mate-panel after killing it?

I do not think there is a way, but I don't know for sure.

**Comment by diegosardina** [comment]
I renamed /usr/bin/mate-panel to something different, so mate couldn't find it anymore :-)

Ok executed with gdb, let's wait

**Comment by diegosardina** [comment]
Both patch are applied, wnck-applet crashed but gdb didn't catch che crash, so I couldn't generate the backtrace.

I used the same trick and run gdb directly on /usr/libexec/mate-applets/wnck-applet (under a different name).

Let's wait

**Comment by diegosardina** [comment]
```
(gdb) bt
#0  0x00007ffff76e870a in  () at /usr/lib64/libgdk-3.so.0
#1  0x00007ffff76bd780 in gdk_device_get_window_at_position_double () at /usr/lib64/libgdk-3.so.0
#2  0x00007ffff76bd89d in gdk_device_get_window_at_position () at /usr/lib64/libgdk-3.so.0
#3  0x00007ffff7a9539f in gtk_tooltip_trigger_tooltip_query () at /usr/lib64/libgtk-3.so.0
#4  0x00007ffff7224b00 in g_slist_foreach () at /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff7ad2b81 in  () at /usr/lib64/libgtk-3.so.0
#6  0x00007ffff76b9399 in  () at /usr/lib64/libgdk-3.so.0
#7  0x00007ffff7205b83 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#8  0x00007ffff7205f10 in  () at /usr/lib64/libglib-2.0.so.0
#9  0x00007ffff72061c3 in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#10 0x00007ffff79915d5 in gtk_main () at /usr/lib64/libgtk-3.so.0
#11 0x00007ffff7f876ce in _mate_panel_applet_factory_main_internal
   Python Exception <class 'gdb.error'>: No type named TypeNode.
 (factory_id=factory_id@entry=0x5555555610e0 "WnckletFactory", out_process=out_process@entry=1, applet_type=, callback=callback@entry=0x55555555b129 <wncklet_factory>, user_data=user_data@entry=0x0) at mate-panel-applet.c:2458
#12 0x00007ffff7f8a1ba in mate_panel_applet_factory_main
    (factory_id=factory_id@entry=0x5555555610e0 "WnckletFactory", out_process=out_process@entry=1, applet_type=<optimized out>, callback=callback@entry=0x55555555b129 <wncklet_factory>, user_data=user_data@entry=0x0) at mate-panel-applet.c:2486
#13 0x000055555555b797 in main (argc=<optimized out>, argv=<optimized out>) at wncklet.c:155
(gdb) 

```

**Comment by gadefox** [comment]
The same issue on Debian 11 and I can't find any pattern..

**Comment by raveit65** [comment]
For fedora we reverted an upstream commit of  libwnck-40.0 version to avoid this problem https://github.com/mate-desktop/mate-panel/issues/1230  with workspace-switcher
https://src.fedoraproject.org/rpms/libwnck3/blob/f34/f/libwnck_0001-Revert-pager-do-not-change-workspace-size-from-size_.patch
Not sure if this related
Mate-Panel-1.26 in fedora is patched with mentioned commits of this topic.
And i can't reproduce a crash of wnck-applets on several machines.
Any way, i will do a 1.26.1 release with fixes from master.

**Comment by diegosardina** [comment]
> For fedora we reverted an upstream commit of libwnck-40.0 version to avoid this problem #1230 with workspace-switcher
> https://src.fedoraproject.org/rpms/libwnck3/blob/f34/f/libwnck_0001-Revert-pager-do-not-change-workspace-size-from-size_.patch

In gentoo I use libwnck 3.36.0 that seems already to have the code in that patch

**Comment by raveit65** [comment]
mate-panel-1.26.1 is released, please test.

**Comment by tofurky** [comment]
I've been experiencing the same with the 1.26.0-0ubuntu1~focal2.0 (x86_64) packages from the Fresh MATE PPA. Using marco + compton on NVIDIA 470.74.

I locally built 1.26.1 as well, and it is also showing the same crash.

The backtrace looks very similar to the others shared in this thread. I installed debugging symbols and was able to get the line numbers and some other info:

<details><summary>1.26.1 backtrace (click to expand)</summary>

```
Attaching to process 476928
[New LWP 476929]
[New LWP 476930]
[New LWP 476931]
[New LWP 476932]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007b513ad95aff in __GI___poll (fds=0x64fbd8e3d4c0, nfds=3, timeout=5637) at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) cont
Continuing.
[Thread 0x7b5133fff700 (LWP 476931) exited]
[New Thread 0x7b5133fff700 (LWP 476944)]
[Thread 0x7b5133fff700 (LWP 476944) exited]

Thread 1 "wnck-applet" received signal SIGSEGV, Segmentation fault.
0x00007b513b3c7888 in gdk_x11_device_xi2_window_at_position (device=<optimized out>, win_x=0x7fffc09a5868, win_y=0x7fffc09a5870, mask=0x0, get_toplevel=0) at ../../../../../gdk/x11/gdkdevice-xi2.c:661
661	../../../../../gdk/x11/gdkdevice-xi2.c: No such file or directory.
(gdb) bt full
#0  0x00007b513b3c7888 in gdk_x11_device_xi2_window_at_position (device=<optimized out>, win_x=0x7fffc09a5868, win_y=0x7fffc09a5870, mask=0x0, get_toplevel=0) at ../../../../../gdk/x11/gdkdevice-xi2.c:661
        impl = 0x0
        device_xi2 = <optimized out>
        display = 0x64fbd8d830e0 [GdkX11Display]
        screen = <optimized out>
        xdisplay = 0x64fbd8d6f210
        window = 0x64fbd907b730
        xwindow = 0
        root = 657
        child = 12695585
        last = 58720259
        xroot_x = 231
        xroot_y = 56
        xwin_x = 231
        xwin_y = 10
        button_state = {mask_len = 4, mask = 0x64fbd9070b50 "\020\363\030\331\373d"}
        mod_state = {base = 0, latched = 0, locked = 0, effective = 0}
        group_state = {base = 0, latched = 0, locked = 0, effective = 0}
        retval = <optimized out>
#1  0x00007b513b39b39c in _gdk_device_window_at_position (get_toplevel=0, mask=0x0, win_y=0x7fffc09a5870, win_x=0x7fffc09a5868, device=0x64fbd8da3020 [GdkX11DeviceXI2]) at ../../../../gdk/gdkdevice.c:1894
        tmp_x = 6.698977400902613e-310
        tmp_y = 5.4857512607641299e-310
        window = <optimized out>
        __func__ = "gdk_device_get_window_at_position_double"
#2  gdk_device_get_window_at_position_double (device=0x64fbd8da3020 [GdkX11DeviceXI2], win_x=win_x@entry=0x7fffc09a58b8, win_y=win_y@entry=0x7fffc09a58c0) at ../../../../gdk/gdkdevice.c:680
        tmp_x = 6.698977400902613e-310
        tmp_y = 5.4857512607641299e-310
        window = <optimized out>
        __func__ = "gdk_device_get_window_at_position_double"
#3  0x00007b513b39b4c1 in gdk_device_get_window_at_position (device=<optimized out>, win_x=win_x@entry=0x7fffc09a58f8, win_y=win_y@entry=0x7fffc09a58fc) at ../../../../gdk/gdkdevice.c:725
        tmp_x = 5.4857510589885106e-310
        tmp_y = 5.4857510713535903e-310
        window = <optimized out>
#4  0x00007b513b7be683 in gtk_tooltip_trigger_tooltip_query (display=<optimized out>) at ../../../../gtk/gtktooltip.c:446
        x = 971112465
        y = 31569
        window = <optimized out>
         event = 
            {type = -656997264, any = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377'}, expose = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', area = {x = 0, y = -653965808, width = 25851, height = -656024048}, region = 0x25cea9e2d4d3ff00, count = -653965808}, visibility = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', state = GDK_VISIBILITY_UNOBSCURED}, motion = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', time = 0, x = 5.4857512085994932e-310, y = 5.4857511069089257e-310, axes = 0x25cea9e2d4d3ff00, state = 3641001488, is_hint = 25851, device = 0x64fbd9054610, x_root = 5.4857512085994932e-310, y_root = 6.6989764926749278e-310}, button = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', time = 0, x = 5.4857512085994932e-310, y = 5.4857511069089257e-310, axes = 0x25cea9e2d4d3ff00, state = 3641001488, button = 25851, device = 0x64fbd9054610, x_root = 5.4857512085994932e-310, y_root = 6.6989764926749278e-310}, touch = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', time = 0, x = 5.4857512085994932e-310, y = 5.4857511069089257e-310, axes = 0x25cea9e2d4d3ff00, state = 3641001488, sequence = 0x64fbd9054610, emulating_pointer = -653965808, device = 0x7b5139e242f3, x_root = 5.4857510585932581e-310, y_root = 5.4857512085994932e-310}, scroll = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', time = 0, x = 5.4857512085994932e-310, y = 5.4857511069089257e-310, state = 3570663168, direction = 634300898, device = 0x64fbd9054610, x_root = 5.4857512085994932e-310, y_root = 5.4857512085994932e-310, delta_x = 6.6989764926749278e-310, delta_y = 5.4857510585932581e-310, is_stop = 0}, key = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', time = 0, state = 3641001488, keyval = 25851, length = -656024048, string = 0x25cea9e2d4d3ff00 <error: Cannot access memory at address 0x25cea9e2d4d3ff00>, hardware_keycode = 17936, group = 5 '\005', is_modifier = 1}, crossing = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', subwindow = 0x64fbd9054610, time = 3638943248, x = 1.4155826200005319e-126, y = 5.4857512085994932e-310, x_root = 5.4857512085994932e-310, y_root = 5.4857512085994932e-310, mode = 971129587, detail = 31569, focus = -657001968, state = 25851}, focus_change = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', in = 32767}, configure = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', x = 0, y = -653965808, width = 25851, height = -656024048}, property = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', atom = 0x64fbd9054610, time = 3638943248, state = 25851}, selection = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', selection = 0x64fbd9054610, target = 0x64fbd8e5de10, property = 0x25cea9e2d4d3ff00, time = 3641001488, requestor = 0x64fbd9054610}, owner_change = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', owner = 0x64fbd9054610, reason = (unknown: 3638943248), selection = 0x25cea9e2d4d3ff00, time = 3641001488, selection_time = 25851}, proximity = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', time = 0, device = 0x64fbd9054610}, dnd = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', context = 0x64fbd9054610, time = 3638943248, x_root = 25851, y_root = 0}, window_state = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', changed_mask = (unknown: 0), new_window_state = (GDK_WINDOW_STATE_FULLSCREEN | GDK_WINDOW_STATE_TOP_TILED | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE | unknown: 3640918016)}, setting = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', action = GDK_SETTING_ACTION_NEW, name = 0x64fbd9054610 "\001"}, grab_broken = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', keyboard = 0, implicit = -653965808, grab_window = 0x64fbd8e5de10}, touchpad_swipe = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', phase = -1 '\377', n_fingers = -1 '\377', time = 0, x = 5.4857512085994932e-310, y = 5.4857511069089257e-310, dx = 1.4155826200005319e-126, dy = 5.4857512085994932e-310, x_root = 5.4857512085994932e-310, y_root = 5.4857512085994932e-310, state = 971129587}, touchpad_pinch = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', phase = -1 '\377', n_fingers = -1 '\377', time = 0, x = 5.4857512085994932e-310, y = 5.4857511069089257e-310, dx = 1.4155826200005319e-126, dy = 5.4857512085994932e-310, angle_delta = 5.4857512085994932e-310--Type <RET> for more, q to quit, c to continue without paging--
, scale = 5.4857512085994932e-310, x_root = 6.6989764926749278e-310, y_root = 5.4857510585932581e-310, state = 3641001488}, pad_button = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', time = 0, group = 3641001488, button = 25851, mode = 3638943248}, pad_axis = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', time = 0, group = 3641001488, index = 25851, mode = 3638943248, value = 1.4155826200005319e-126}, pad_group_mode = {type = -656997264, window = 0x25cea9e2d4d3ff00, send_event = -1 '\377', time = 0, group = 3641001488, mode = 25851}}
        device = <optimized out>
#5  0x00007b513aef6c70 in g_slist_foreach (list=<optimized out>, func=0x7b513b7be640 <gtk_tooltip_trigger_tooltip_query>, user_data=user_data@entry=0x0) at ../../../glib/gslist.c:880
        next = 0x0
#6  0x00007b513b7fb5cd in tooltip_query_idle (data=<optimized out>) at ../../../../gtk/gtkwidget.c:15397
#7  0x00007b513b396f4d in gdk_threads_dispatch (data=0x64fbd8ebb240) at ../../../../gdk/gdk.c:769
        dispatch = 0x64fbd8ebb240
        ret = 0
#8  0x00007b513aed704e in g_main_dispatch (context=0x64fbd8da2660) at ../../../glib/gmain.c:3309
        dispatch = 0x7b513aed3360 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x64fbd8ebb240
        callback = 0x7b513b396f20 <gdk_threads_dispatch>
        cb_funcs = 0x7b513afac280 <g_source_callback_funcs>
        cb_data = 0x64fbd8ffcb80
        need_destroy = <optimized out>
        source = 0x64fbd9156260
        current = 0x64fbd8dd83f0
        i = 0
        __func__ = "g_main_dispatch"
#9  g_main_context_dispatch (context=context@entry=0x64fbd8da2660) at ../../../glib/gmain.c:3974
#10 0x00007b513aed7400 in g_main_context_iterate (context=0x64fbd8da2660, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4047
        max_priority = 200
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x64fbd8e3d4c0
#11 0x00007b513aed76f3 in g_main_loop_run (loop=0x64fbd8e3d4a0) at ../../../glib/gmain.c:4241
        __func__ = "g_main_loop_run"
#12 0x00007b513b6b937d in gtk_main () at ../../../../gtk/gtkmain.c:1328
        loop = 0x64fbd8e3d4a0
#13 0x00007b513bcb8e28 in _mate_panel_applet_factory_main_internal
    (factory_id=<optimized out>, out_process=1, applet_type=0x64fbd9040ab0 [MatePanelApplet/GtkEventBox/GtkBin/GtkContainer/GtkWidget/GInitiallyUnowned], callback=<optimized out>, user_data=0x0) at mate-panel-applet.c:2458
        factory = 0x64fbd8e01180 [MatePanelAppletFactory]
        closure = 0x64fbd9040b80
        __func__ = "_mate_panel_applet_factory_main_internal"
#14 0x000064fbd70834a6 in main (argc=<optimized out>, argv=<optimized out>) at wncklet.c:155
        context = 0x64fbd8d63660
        error = 0x0
        retval = <optimized out>
```
</details>

It appears that in gdk_x11_device_xi2_window_at_position there's a NULL deference of `impl` (https://salsa.debian.org/gnome-team/gtk3/-/blob/ubuntu/3.24.20-1ubuntu1/gdk/x11/gdkdevice-xi2.c#L661):
```
(gdb) print impl
$1 = 0x0
(gdb) print impl->window_scale
Cannot access memory at address 0x44
(gdb) print window
$2 = 0x64fbd907b730
(gdb) print *window
$3 = {parent_instance = {g_type_instance = {g_class = <error reading variable: Cannot access memory at address 0x0>}, ref_count = 0, qdata = 0x0}, impl = 0x0, parent = 0x0, transient_for = 0x0, visual = 0x64fbd8d97990 [GdkX11Visual], 
  user_data = 0x0, x = 0, y = 22, event_mask = 98304, window_type = 4 '\004', depth = 32 ' ', resize_count = 0 '\000', toplevel_window_type = -1 '\377', filters = 0x0, children = 0x0, 
  children_list_node = {data=0x64fbd907b730, next=0x0, prev=0x0}, native_children = 0x0, background = 0x0, current_paint = {surface = 0x0, region = 0x0, flushed_region = 0x0, need_blend_region = 0x0, surface_needs_composite = 0, 
    use_gl = 0}, gl_paint_context = 0x0, update_area = 0x0, update_freeze_count = 0, active_update_area = 0x0, old_updated_area = {0x0, 0x0}, old_state = (unknown: 0), state = GDK_WINDOW_STATE_WITHDRAWN, 
  synthesized_crossing_event_id = 0, alpha = 0 '\000', fullscreen_mode = 0 '\000', input_only = 0, pass_through = 0, modal_hint = 0, composited = 0, has_alpha_background = 0, destroyed = 1, accept_focus = 0, focus_on_map = 0, 
  shaped = 0, support_multidevice = 0, effective_visibility = 0, visibility = 0, native_visibility = 0, viewable = 1, applied_shape = 0, in_update = 0, geometry_dirty = 1, event_compression = 0, frame_clock_events_paused = 0, 
  impl_window = 0x64fbd907b730, update_and_descendants_freeze_count = 0, abs_x = 0, abs_y = 0, width = 1920, height = 1010, shadow_top = 0, shadow_left = 0, shadow_right = 0, shadow_bottom = 0, num_offscreen_children = 0, 
  clip_region = 0x0, cursor = 0x0, device_cursor = 0x64fbd90148c0<error reading variable: Cannot access memory at address 0x3fea5a5a5a5a5a5a>, shape = 0x0, input_shape = 0x0, devices_inside = 0x0, device_events = 0x0, 
  source_event_masks = 0x0, device_added_handler_id = 0, device_changed_handler_id = 0, frame_clock = 0x0, invalidate_handler = 0x0, drawing_context = 0x0, opaque_region = 0x0}
```

The relevant lines:
```
  if (win_x)
    *win_x = (window) ? (xwin_x / impl->window_scale) : -1;
```

On a hunch I reverted these two commits, and have not had a crash in a few days. Reinstalling 1.26.1 causes crashes to happen within an hour or two:

https://github.com/mate-desktop/mate-panel/commit/c4a5e775da5b592e82a79fcb5e09b1f2fe86567a "wncklet: search the window before creating a new one"
https://github.com/mate-desktop/mate-panel/commit/06292db3c2b9a4ad81c7063c7bcff7cb6c0f927a "wncklet: remove extra ref on gdk_x11_window_foreign_new_for_display"

I'm not able to reliably reproduce it (and it's happened overnight with my screen locked), but one thing that did trigger it (not reproducibly) was opening a URL (Chrome) from mate-terminal.

I'll report back if I do happen to have another crash with those two commits reverted, but so far so good.

**Comment by zhuyaliang** [comment]
@tofurky It may be a problem releasing the reference count，I need to do some tests. If the test goes well, I will reply to you

**Comment by gadefox** [comment]
I build the version 1.26 w/ the same result. Also I suddenly can't create `gir` file on 32-bit OS (Debian 11) anymore!
```
g-ir-scanner: warning: Option --strip-prefix has been deprecated;
see --identifier-prefix and --symbol-prefix.
/usr/lib/gcc/i686-linux-gnu/10/include/stddef.h:424: syntax error, unexpected identifier in '  __float128 __max_align_f128 __attribute__((__aligned__(__alignof(__float128))));' at '__float128'
mate-panel-applet-gsettings.h:34: Warning: MatePanelApplet: symbol='PANEL_OBJECT_PREFS_PATH': Unknown namespace for symbol 'PANEL_OBJECT_PREFS_PATH'
```

**Comment by tofurky** [comment]
> @tofurky Did the crash happen？I use `archlinux mate-1.26.1` After a lot of testing, there was no crash,Next, I'll switch to `Ubuntu` for testing

Not a single crash since reverting those two commits.

**Comment by tofurky** [comment]
> @tofurky I'd like to debug this issue on `Debian 11`. Which app did you launch using gdb? Should I build debug version of `libwnck` too?

I did not run the app under gdb, I attached to the process as root using `gdb -p pid` where pid is the pid of wnck-applet. Then type 'cont' in gdb to resume the attached process. Yes, you need debug symbols in order to get a proper stack trace. However, I am confident that the issue everyone encountering is the same, with the same root cause (bad commits). More info on installing debug packages: https://wiki.debian.org/AutomaticDebugPackages

Note that the crash is in the gdk library (part of gtk) so you need to install debug symbols for that to get a proper full stack trace. Take a look at the trace I posted previously to see what I mean.

**Comment by raveit65** [comment]
> Note that the crash is in the gdk library (part of gtk) so you need to install debug symbols for that to get a proper full stack trace. Take a look at the trace I posted previously to see what I mean.

Which version of gtk are you using?

**Comment by tofurky** [comment]
> So, why i didn't get the crash in fedora 34 with gtk3-3.24.30-1.fc34.x86_64 when your statement is clear ? Don't understand me wrong, maybe there is an incompatibility which i don't have gtk3-3.24.30.

No idea.

But I just built 3.24.30-1ubuntu1 from source (from Impish aka 21.10 per https://launchpad.net/ubuntu/+source/gtk+3.0/3.24.30-1ubuntu1) and reinstalled mate-panel 1.26.1 (without the commits reverted) and wnck-applet crashed again within a couple of hours:
```
[New Thread 0x7159c4b30700 (LWP 272307)]
[Thread 0x7159c4b30700 (LWP 272307) exited]

Thread 1 "wnck-applet" received signal SIGSEGV, Segmentation fault.
0x00007159c7b86a48 in gdk_x11_device_xi2_window_at_position (device=<optimized out>, win_x=0x7ffd94d7e688, win_y=0x7ffd94d7e690, mask=0x0, get_toplevel=0) at ../../../../../gdk/x11/gdkdevice-xi2.c:661
661	../../../../../gdk/x11/gdkdevice-xi2.c: No such file or directory.
(gdb) 
Continuing.
[Thread 0x7159b7fff700 (LWP 271112) exited]
[Thread 0x7159c5b32700 (LWP 271109) exited]
[Thread 0x7159c61b9f00 (LWP 271108) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb) 
The program is not being run.
(gdb) bt full
No stack.
```

Will update if I get a proper stack trace, but it appears to be the exact same function (line 661 of gdkdevice-xi2.c)
```
  if (win_x)
    *win_x = (window) ? (xwin_x / impl->window_scale) : -1;
```

**Comment by tofurky** [comment]
<details><summary>1.26.1 backtrace w/gtk 3.24.30-1ubuntu1 (click to expand)</summary>

```
(gdb) cont
Continuing.

Thread 1 "wnck-applet" received signal SIGSEGV, Segmentation fault.
0x00007d26aa901a48 in gdk_x11_device_xi2_window_at_position (device=<optimized out>, win_x=0x7fff1001f3b8, win_y=0x7fff1001f3c0, mask=0x0, get_toplevel=0) at ../../../../../gdk/x11/gdkdevice-xi2.c:661
661	../../../../../gdk/x11/gdkdevice-xi2.c: No such file or directory.
(gdb) bt full
#0  0x00007d26aa901a48 in gdk_x11_device_xi2_window_at_position (device=<optimized out>, win_x=0x7fff1001f3b8, win_y=0x7fff1001f3c0, mask=0x0, get_toplevel=0) at ../../../../../gdk/x11/gdkdevice-xi2.c:661
        impl = 0x0
        device_xi2 = <optimized out>
        display = 0x5e16d3b1a0e0 [GdkX11Display]
        screen = <optimized out>
        xdisplay = 0x5e16d3b060d0
        window = 0x5e16d3d7eac0
        xwindow = 0
        root = 657
        child = 12582940
        last = 52428806
        xroot_x = 944
        xroot_y = 802
        xwin_x = 944
        xwin_y = 756
        button_state = {mask_len = 4, mask = 0x5e16d3c99d90 "\360+\316\323\026^"}
        mod_state = {base = 0, latched = 0, locked = 0, effective = 0}
        group_state = {base = 0, latched = 0, locked = 0, effective = 0}
        retval = <optimized out>
#1  0x00007d26aa8d53fc in _gdk_device_window_at_position (get_toplevel=0, mask=0x0, win_y=0x7fff1001f3c0, win_x=0x7fff1001f3b8, device=0x5e16d3b39820 [GdkX11DeviceXI2]) at ../../../../gdk/gdkdevice.c:1894
        tmp_x = 6.798591282477872e-310
        tmp_y = 5.1112147125444767e-310
        window = <optimized out>
        __func__ = "gdk_device_get_window_at_position_double"
#2  gdk_device_get_window_at_position_double (device=0x5e16d3b39820 [GdkX11DeviceXI2], win_x=win_x@entry=0x7fff1001f408, win_y=win_y@entry=0x7fff1001f410) at ../../../../gdk/gdkdevice.c:680
        tmp_x = 6.798591282477872e-310
        tmp_y = 5.1112147125444767e-310
        window = <optimized out>
        __func__ = "gdk_device_get_window_at_position_double"
#3  0x00007d26aa8d5521 in gdk_device_get_window_at_position (device=<optimized out>, win_x=win_x@entry=0x7fff1001f448, win_y=win_y@entry=0x7fff1001f44c) at ../../../../gdk/gdkdevice.c:725
        tmp_x = 5.1112145324737541e-310
        tmp_y = 5.1112145421052675e-310
        window = <optimized out>
#4  0x00007d26aacfda93 in gtk_tooltip_trigger_tooltip_query (display=<optimized out>) at ../../../../gtk/gtktooltip.c:446
        x = -1456107503
        y = 32038
        window = <optimized out>
 
        event = 
            {type = -743410896, any = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377'}, expose = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', area = {x = 0, y = -740557808, width = 24086, height = -740319216}, region = 0x262b132c620e9400, count = -740557808}, visibility = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', state = GDK_VISIBILITY_UNOBSCURED}, motion = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', time = 0, x = 5.1112146732808822e-310, y = 5.1112146850688933e-310, axes = 0x262b132c620e9400, state = 3554409488, is_hint = 24086, device = 0x5e16d3dbfc10, x_root = 5.1112146732808822e-310, y_root = 6.7985903742501868e-310}, button = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', time = 0, x = 5.1112146732808822e-310, y = 5.1112146850688933e-310, axes = 0x262b132c620e9400, state = 3554409488, button = 24086, device = 0x5e16d3dbfc10, x_root = 5.1112146732808822e-310, y_root = 6.7985903742501868e-310}, touch = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', time = 0, x = 5.1112146732808822e-310, y = 5.1112146850688933e-310, axes = 0x262b132c620e9400, state = 3554409488, sequence = 0x5e16d3dbfc10, emulating_pointer = -740557808, device = 0x7d26a935d2f3, x_root = 5.1112145320871972e-310, y_root = 5.1112146732808822e-310}, scroll = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', time = 0, x = 5.1112146732808822e-310, y = 5.1112146850688933e-310, state = 1645122560, direction = 640357164, device = 0x5e16d3dbfc10, x_root = 5.1112146732808822e-310, y_root = 5.1112146732808822e-310, delta_x = 6.7985903742501868e-310, delta_y = 5.1112145320871972e-310, is_stop = 0}, key = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', time = 0, state = 3554409488, keyval = 24086, length = -740319216, string = 0x262b132c620e9400 <error: Cannot access memory at address 0x262b132c620e9400>, hardware_keycode = 64528, group = 219 '\333', is_modifier = 1}, crossing = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', subwindow = 0x5e16d3dbfc10, time = 3554648080, x = 7.9994219415918489e-125, y = 5.1112146732808822e-310, x_root = 5.1112146732808822e-310, y_root = 5.1112146732808822e-310, mode = 2838876915, detail = 32038, focus = -743415600, state = 24086}, focus_change = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', in = 32767}, configure = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', x = 0, y = -740557808, width = 24086, height = -740319216}, property = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', atom = 0x5e16d3dbfc10, time = 3554648080, state = 24086}, selection = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', selection = 0x5e16d3dbfc10, target = 0x5e16d3dfa010, property = 0x262b132c620e9400, time = 3554409488, requestor = 0x5e16d3dbfc10}, owner_change = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', owner = 0x5e16d3dbfc10, reason = (unknown: 3554648080), selection = 0x262b132c620e9400, time = 3554409488, selection_time = 24086}, proximity = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', time = 0, device = 0x5e16d3dbfc10}, dnd = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', context = 0x5e16d3dbfc10, time = 3554648080, x_root = 24086, y_root = 0}, window_state = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', changed_mask = (unknown: 0), new_window_state = (GDK_WINDOW_STATE_FULLSCREEN | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_TILED | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_TILED | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_TILED | GDK_WINDOW_STATE_LEFT_RESIZABLE | unknown: 3554279424)}, setting = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', action = GDK_SETTING_ACTION_NEW, name = 0x5e16d3dbfc10 "\001"}, grab_broken = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', keyboard = 0, implicit = -740557808, grab_window = 0x5e16d3dfa010}, touchpad_swipe = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', phase = -1 '\377', n_fingers = -1 '\377', time = 0, x = 5.1112146732808822e-310, y = 5.1112146850688933e-310, dx = 7.9994219415918489e-125, dy = 5.1112146732808822e-310, x_root = 5.1112146732808822e-310, y_root = 5.1112146732808822e-310, state = 2838876915}, touchpad_pinch = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', phase = -1 '\377', n_fingers = -1 '\377', time = 0, x = 5.1112146732808822e-310, y = 5.1112146850688933e--Type <RET> for more, q to quit, c to continue without paging--
-310, dx = 7.9994219415918489e-125, dy = 5.1112146732808822e-310, angle_delta = 5.1112146732808822e-310, scale = 5.1112146732808822e-310, x_root = 6.7985903742501868e-310, y_root = 5.1112145320871972e-310, state = 3554409488}, pad_button = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', time = 0, group = 3554409488, button = 24086, mode = 3554648080}, pad_axis = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', time = 0, group = 3554409488, index = 24086, mode = 3554648080, value = 7.9994219415918489e-125}, pad_group_mode = {type = -743410896, window = 0x262b132c620e9400, send_event = -1 '\377', time = 0, group = 3554409488, mode = 24086}}
        device = <optimized out>
#5  0x00007d26aa42fc70 in g_slist_foreach (list=<optimized out>, func=0x7d26aacfda50 <gtk_tooltip_trigger_tooltip_query>, user_data=user_data@entry=0x0) at ../../../glib/gslist.c:880
        next = 0x0
#6  0x00007d26aad3aa7d in tooltip_query_idle (data=<optimized out>) at ../../../../gtk/gtkwidget.c:15397
#7  0x00007d26aa8d0fad in gdk_threads_dispatch (data=0x5e16d3c764a0) at ../../../../gdk/gdk.c:769
        dispatch = 0x5e16d3c764a0
        ret = 0
#8  0x00007d26aa41004e in g_main_dispatch (context=0x5e16d3b37a30) at ../../../glib/gmain.c:3309
        dispatch = 0x7d26aa40c360 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x5e16d3c764a0
        callback = 0x7d26aa8d0f80 <gdk_threads_dispatch>
        cb_funcs = 0x7d26aa4e5280 <g_source_callback_funcs>
        cb_data = 0x5e16d3eb9980
        need_destroy = <optimized out>
        source = 0x5e16d3e81c60
        current = 0x5e16d3b6f730
        i = 0
        __func__ = "g_main_dispatch"
#9  g_main_context_dispatch (context=context@entry=0x5e16d3b37a30) at ../../../glib/gmain.c:3974
#10 0x00007d26aa410400 in g_main_context_iterate (context=0x5e16d3b37a30, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4047
        max_priority = 200
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x5e16d3df5fa0
#11 0x00007d26aa4106f3 in g_main_loop_run (loop=0x5e16d3df5f80) at ../../../glib/gmain.c:4241
        __func__ = "g_main_loop_run"
#12 0x00007d26aabf7ecd in gtk_main () at ../../../../gtk/gtkmain.c:1329
        loop = 0x5e16d3df5f80
#13 0x00007d26ab26ee28 in _mate_panel_applet_factory_main_internal
    (factory_id=<optimized out>, out_process=1, applet_type=0x5e16d3ddd2b0 [MatePanelApplet/GtkEventBox/GtkBin/GtkContainer/GtkWidget/GInitiallyUnowned], callback=<optimized out>, user_data=0x0) at mate-panel-applet.c:2458
        factory = 0x5e16d3c99120 [MatePanelAppletFactory]
        closure = 0x5e16d3de6e20
        __func__ = "_mate_panel_applet_factory_main_internal"
#14 0x00005e16d32c44a6 in main (argc=<optimized out>, argv=<optimized out>) at wncklet.c:155
        context = 0x5e16d3afa660
        error = 0x0
        retval = <optimized out>
(gdb) print window->parent
$2 = 0x0
(gdb) print window->parent_instance->ref_count
$3 = 0
```
</details>

**Comment by anvltu** [comment]
This random crashes make me mad. Ubuntu 21.10.

**Comment by UweSauter** [comment]
Still happening on Arch with
mate-panel 1.26.1-1
libwnck3 40.0-1
gtk3 1:3.24.31-1

```
           PID: 48417 (wnck-applet)
           UID: 1000 (myuser)
           GID: 1000 (myuser)
        Signal: 11 (SEGV)
     Timestamp: Tue 2022-01-11 11:38:41 CET (26min ago)
  Command Line: /usr/lib/mate-panel/wnck-applet
    Executable: /usr/lib/mate-panel/wnck-applet
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/dbus.service
          Unit: user@1000.service
     User Unit: dbus.service
         Slice: user-1000.slice
     Owner UID: 1000 (myuser)
       Boot ID: 679cad728dd8462e97a097144e29b84a
    Machine ID: fbf3b39530714781a43e127ea27ed859
      Hostname: myuser-t14
       Storage: /var/lib/systemd/coredump/core.wnck-applet.1000.679cad728dd8462e97a097144e29b84a.48417.1641897521000000.zst (present)
     Disk Size: 1.7M
       Message: Process 48417 (wnck-applet) of user 1000 dumped core.

                Module linux-vdso.so.1 with build-id 035c7da8b451e8d19aed30c8ca3970d363e14060
                Module ISO8859-1.so with build-id d93c01aecc9ab9b0749df9c7d43dd05dd3887577
                Module libdconfsettings.so with build-id 7a4ba7af122c4d11168004a9ea6def330f02089f
                Module libgvfscommon.so with build-id 90d1858292300e4e1ee3fbe84ab06079af840ec6
                Module libgvfsdbus.so with build-id dcb9d652f2e5c65154517fe6934215ec6bd1c29c
                Module libogg.so.0 with build-id ca0cae30a809f10db1f16e54a23b4e5ff7b2c54c
                Module libvorbis.so.0 with build-id ad0a6c1af8f219b4e314090b6e8847223d424cbe
                Module libltdl.so.7 with build-id 64bc54a40a0b6e4209a2c712364b4ae653c3f5b2
                Module libtdb.so.1 with build-id bec061530310665480ee91395b4eb0a937750a03
                Module libvorbisfile.so.3 with build-id 0010b21da05e318b42e718d90738febf58028141
                Module libcanberra.so.0 with build-id 379ed64f9d1408a83806cd5d94dc5bb903765615
                Module libcanberra-gtk3.so.0 with build-id 133409dc3e744fe0edc6a4d078714dce82dacf98
                Module libcanberra-gtk-module.so with build-id 72bd14fd5ba4fb0eda082b3daeccc80b796a5586
                Module libgpg-error.so.0 with build-id 3801187d42c4955bd93c605451430cdf1b164e63
                Module libgcrypt.so.20 with build-id db45f5d5e0f7af1e77324fea1885f974619ad268
                Module libcap.so.2 with build-id f56c6cd6ad4d35053340d7ff2f8f954498796739
                Module liblz4.so.1 with build-id e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                Module libbrotlicommon.so.1 with build-id a4ba3f4b4571c8272343b621da812a6e24a202a7
                Module libgcc_s.so.1 with build-id 7f8508bb914546ada778809b64b99d234337d835
                Module libstdc++.so.6 with build-id 9b5eeeb149bf3c4efe787fb398b44f00507aec87
                Module libicudata.so.70 with build-id e1dcc2a88cfaafed882d09c90c668af0eed4efed
                Module libsystemd.so.0 with build-id b86eb3142e9f930340715a0f090da03edbb24f9b
                Module libdatrie.so.1 with build-id 6fe3b6ece2c8e7d11869fa051375128d8f808f58
                Module libblkid.so.1 with build-id 057b6bc8eebd42d1f5cafe4f4ac72646aae1f2c5
                Module liblzma.so.5 with build-id 8b615460aa230708c5183f16bede67aa0437d95e
                Module libzstd.so.1 with build-id 6214183688018e3fba6d66db10c2c8d0b45e0578
                Module libXdmcp.so.6 with build-id 8ca0792d23c8b8b4c0864297512349292bea5955
                Module libXau.so.6 with build-id 1c67764663e07bec24d8951e5fd93f4d165979ff
                Module libbrotlidec.so.1 with build-id 45defc036e918e0140a72f1fbce6e7692d38241d
                Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                Module libxml2.so.2 with build-id b710b880b0d4e9c93554fa632129db44c20632cd
                Module libjson-glib-1.0.so.0 with build-id 5865be5fcc01b48a0a113e0145ec45529bff89a6
                Module libsqlite3.so.0 with build-id 5f711261aabe285f02a673ded77a37b413afbfa2
                Module libicui18n.so.70 with build-id 95af755fca990df26753a7d720b8e3ae24270e42
                Module libicuuc.so.70 with build-id 2e245c2bf12f95fd8ab79b3a4be99524677cbd70
                Module libstemmer.so.0 with build-id aa44a40dfb223020ed8e49cd2d28fc3887128463
                Module libatspi.so.0 with build-id de251156cf6f2f447c5e2b8721bd913d79995d4f
                Module libdbus-1.so.3 with build-id 74f2ab9c60512f3a93c932c3f627564d42e0b11e
                Module libexpat.so.1 with build-id 16023a53e7b5bbdff92bd0bf2eebd36f9b5b879f
                Module libgraphite2.so.3 with build-id 47761dc11e553f519cde97ed9ee985be12ccdae2
                Module libX11-xcb.so.1 with build-id 0db4f94d8ae31b8dc9a83f825a9171656f1e532c
                Module libxcb-util.so.1 with build-id 4188ebc629b472b560849c5792a69c1803c3d1a4
                Module libthai.so.0 with build-id a7ac5010b4275c49308021200d23690533952702
                Module libdl.so.2 with build-id 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                Module ld-linux-x86-64.so.2 with build-id 040cc3dd10461562f177df39e3be2f3704258c3c
                Module libpcre.so.1 with build-id 845483dd0acba86de9f0313102bebbaf3ce52767
                Module libffi.so.8 with build-id f90d8b734f6de9b25faedb8cbfab7054dafc0a42
                Module libresolv.so.2 with build-id c915c72668282861a813f7ea3c0780f37b681dc0
                Module libmount.so.1 with build-id 39e178b712b6635a8681182f7a9fbb64e6074aee
                Module libtiff.so.5 with build-id e8d89a0fb0847641ddb75c5f03fa89d68155a75d
                Module libjpeg.so.8 with build-id 879ca18a2f58c25d77ba881db3a44a5676ef6c7d
                Module libpixman-1.so.0 with build-id 341f793dcada3a48a306a793d265a517e3f2e7d6
                Module libxcb-shm.so.0 with build-id fb797f299a446f559a95afcc168227482cc800d1
                Module libxcb-render.so.0 with build-id a37bdb37744b508be9dd29fd9ccb9bb0170d43e5
                Module libxcb.so.1 with build-id 0d1ef11740a5daad2ee331e812a51aa6574af222
                Module libfreetype.so.6 with build-id 26c5f833068ff72660d1975cbc2074c3eb47fad8
                Module libpng16.so.16 with build-id 2dc0bce07f199bf983c07a05fb95a6f4af83a9b3
                Module libz.so.1 with build-id 0c1459c56513efd5d53eb3868290e9afee6a6a26
                Module libXinerama.so.1 with build-id dbb6adece34ea2766d3efcd628af8f9757344dd6
                Module libXcomposite.so.1 with build-id f1bb5ffb6203ab2907ac044a204ce3902a79f1c1
                Module libXdamage.so.1 with build-id a1d867e093c16944b2c0083be98050ef35c9e5c2
                Module libXcursor.so.1 with build-id eb6315bcd7526aaf51b0a1307efdc587cea0a152
                Module libXext.so.6 with build-id d70f24beb4fad748d6becffdcc13e51be0a2ebfa
                Module libwayland-egl.so.1 with build-id 791e39283cdcc5a08cfd091b8cd4c59869a11278
                Module libwayland-cursor.so.0 with build-id 79d7e67af210407c2afe92ba8c189c8648a6474c
                Module libxkbcommon.so.0 with build-id 1f1bc7527e57c886c3df5803068122e1971d4724
                Module librt.so.1 with build-id 75484da2d6f1515189eefa076e0a40328834cd16
                Module libpthread.so.0 with build-id 07c8f95b4f3251d08550217ad8a1f31066229996
                Module libXfixes.so.3 with build-id 0a05c7e8714522bfbdd7c0027c3e2a94965664b0
                Module libtracker-sparql-3.0.so.0 with build-id b0eee5a9b660fed5221ea15139e9608282320503
                Module libcloudproviders.so.0 with build-id ed1d9c9e60be4e858ad148484767249be1edf95f
                Module libatk-bridge-2.0.so.0 with build-id 1161ebbcc5aa791075dfa026671875e5417287bd
                Module libXi.so.6 with build-id 16603be937a02a7e61b0b0395d064be7efd86f49
                Module libepoxy.so.0 with build-id b6357fc6b748c512f90339433d74502b9d0621dc
                Module libfribidi.so.0 with build-id 79124bad061c2aab4ec89f25d067363d5b781114
                Module libfontconfig.so.1 with build-id 1103a641395c7d3b42e49b793d3a9ea927c77bf6
                Module libpangoft2-1.0.so.0 with build-id ef74c3ce7ee52a746fb5f2840d80a84e314edb92
                Module libharfbuzz.so.0 with build-id 1d9dee49dd99162c3f83eb3259c3c88c6b4cd7fe
                Module libpangocairo-1.0.so.0 with build-id 10d2af38056eee9a6b3458d8aac24095c4dfab72
                Module libgmodule-2.0.so.0 with build-id 5da4523e8d6b5c244a0193e27093d1e61f6ac9e4
                Module libdconf.so.1 with build-id 4e1bd6ba12d7f2997624fe360181059f73e5c84a
                Module libXrandr.so.2 with build-id d4e869b5c72541e1de8f96b456248987ea52d51b
                Module libXRes.so.1 with build-id 6ae98691f3ebed4aae1d0ac919078baa00d71fb6
                Module libstartup-notification-1.so.0 with build-id c31cad1791f13615a8f6c9ec025e1a3c3eef7736
                Module libpango-1.0.so.0 with build-id 730a8183a36afae82dd6a5564c0e490fed239a40
                Module libXrender.so.1 with build-id 97e0b9ab6ba96ebc86527cc2b3c3078aad8616b3
                Module libm.so.6 with build-id 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                Module libX11.so.6 with build-id 5ba5798d193c0065014b8c6252a0678671c8d478
                Module libcairo-gobject.so.2 with build-id abbf5a8a182ea1b8b7d68540df5c2e25c0bdae0c
                Module libc.so.6 with build-id 4b406737057708c0e4c642345a703c47a61c73dc
                Module libwayland-client.so.0 with build-id 0a237f2fd096bada4ca381eec5d64474c4078be4
                Module libglib-2.0.so.0 with build-id 220436a4e27f39372710df014d2517c0387eefa4
                Module libgobject-2.0.so.0 with build-id e67b3a29cecdd98c3d8bd6eb7524a812331b20a2
                Module libgio-2.0.so.0 with build-id bce5a3881708e1e885fa1c9c32e2769a6447c411
                Module libgdk_pixbuf-2.0.so.0 with build-id ca4beb15a30de8d8767f7bca8222038c61b58b36
                Module libcairo.so.2 with build-id 06820af9cf79c2deb207d9533a61caf04e67a8ad
                Module libatk-1.0.so.0 with build-id aacaa40363d304858b654728a893bc212a4ca119
                Module libgdk-3.so.0 with build-id 6f77a9486fc38cb4e374d862662cb5e39ca3988a
                Module libgtk-3.so.0 with build-id e17042e459bfe2a5cd401828a90435a81a82b70d
                Module libmate-desktop-2.so.17 with build-id 53bfb1ce206f2f3aafc7847893cf7cbad72eff72
                Module libwnck-3.so.0 with build-id cd4636b431b6e569e2376d08278b0aff5df07f36
                Module libmate-panel-applet-4.so.1 with build-id e8e7e977c3735f9ac5075364536099de7f79d446
                Module wnck-applet with build-id 8e703aac62cd92b5324caf47e53db4d82b160b54
                Stack trace of thread 48417:
                #0  0x00007fa0370f6bfe n/a (libgdk-3.so.0 + 0x7bbfe)
                #1  0x00007fa0370ac39c gdk_device_get_window_at_position_double (libgdk-3.so.0 + 0x3139c)
                #2  0x00007fa0370ac4be gdk_device_get_window_at_position (libgdk-3.so.0 + 0x314be)
                #3  0x00007fa037459122 gtk_tooltip_trigger_tooltip_query (libgtk-3.so.0 + 0x2e8122)
                #4  0x00007fa036bfb740 g_slist_foreach (libglib-2.0.so.0 + 0x71740)
                #5  0x00007fa0374a16ca n/a (libgtk-3.so.0 + 0x3306ca)
                #6  0x00007fa0370a85dc n/a (libgdk-3.so.0 + 0x2d5dc)
                #7  0x00007fa036bdefd3 g_main_context_dispatch (libglib-2.0.so.0 + 0x54fd3)
                #8  0x00007fa036c35049 n/a (libglib-2.0.so.0 + 0xab049)
                #9  0x00007fa036bde523 g_main_loop_run (libglib-2.0.so.0 + 0x54523)
                #10 0x00007fa03734493f gtk_main (libgtk-3.so.0 + 0x1d393f)
                #11 0x00007fa0379b0c1b n/a (libmate-panel-applet-4.so.1 + 0x7c1b)
                #12 0x000055e88084115a n/a (wnck-applet + 0x715a)
                #13 0x00007fa0369d1b25 __libc_start_main (libc.so.6 + 0x27b25)
                #14 0x000055e8808411be n/a (wnck-applet + 0x71be)

                Stack trace of thread 48460:
                #0  0x00007fa036a9db2f __poll (libc.so.6 + 0xf3b2f)
                #1  0x00007fa036c34fd6 n/a (libglib-2.0.so.0 + 0xaafd6)
                #2  0x00007fa036bdc545 g_main_context_iteration (libglib-2.0.so.0 + 0x52545)
                #3  0x00007fa031c4bebe n/a (libdconfsettings.so + 0x5ebe)
                #4  0x00007fa036c0e905 n/a (libglib-2.0.so.0 + 0x84905)
                #5  0x00007fa036282259 start_thread (libpthread.so.0 + 0x9259)
                #6  0x00007fa036aa85e3 __clone (libc.so.6 + 0xfe5e3)

                Stack trace of thread 48426:
                #0  0x00007fa036a9db2f __poll (libc.so.6 + 0xf3b2f)
                #1  0x00007fa036c34fd6 n/a (libglib-2.0.so.0 + 0xaafd6)
                #2  0x00007fa036bde523 g_main_loop_run (libglib-2.0.so.0 + 0x54523)
                #3  0x00007fa036e290fc n/a (libgio-2.0.so.0 + 0x1080fc)
                #4  0x00007fa036c0e905 n/a (libglib-2.0.so.0 + 0x84905)
                #5  0x00007fa036282259 start_thread (libpthread.so.0 + 0x9259)
                #6  0x00007fa036aa85e3 __clone (libc.so.6 + 0xfe5e3)

                Stack trace of thread 48425:
                #0  0x00007fa036a9db2f __poll (libc.so.6 + 0xf3b2f)
                #1  0x00007fa036c34fd6 n/a (libglib-2.0.so.0 + 0xaafd6)
                #2  0x00007fa036bdc545 g_main_context_iteration (libglib-2.0.so.0 + 0x52545)
                #3  0x00007fa036bdc592 n/a (libglib-2.0.so.0 + 0x52592)
                #4  0x00007fa036c0e905 n/a (libglib-2.0.so.0 + 0x84905)
                #5  0x00007fa036282259 start_thread (libpthread.so.0 + 0x9259)
                #6  0x00007fa036aa85e3 __clone (libc.so.6 + 0xfe5e3)
                ELF object binary architecture: AMD x86-64
 ```

**Comment by paulmelis** [comment]
Same here, multiple times a day. 

mate-panel 1.26.1-1, gtk3 1:3.24.31-1

**Comment by suraw00t** [comment]
Same here, on Debian 12 (bookworm)
mate-panel 1.26.0-1

**Comment by raveit65** [comment]
People with mate-panel-1.26.1 running, can you please create a fresh new account and try to reproduce the issue?
I am thinking windows-list-applet problem is fixed with mate-panel-1.26.1, but we have a problem old/new dconf settings.
I guess, it is the same issue https://github.com/mate-desktop/mate-panel/issues/1249

**Comment by UweSauter** [comment]
Can you point me to the file(s) that need to be removed when I want to keep my account? Is it `~/.config/dconf/*`?

**Comment by raveit65** [comment]
Yes, it is `~/.config/dconf/user` and `/run/user/1000/dconf/user`.
I would delete them from konsole when not logged in, and as root.
But keep in mind that you will lost all dconf settings.
So please test that a new account doesn't have this issue first.
And maybe a simple `mate-panel --reset --replace` is sufficient.

**Comment by paulmelis** [comment]
> And maybe a simple mate-panel --reset --replace is sufficient.

For me, doing a `mate-panel --reset --replace` (and then putting back all launch icons and applets on my top panel, sigh) did *not* make those crashes go away, still seeing them

**Comment by mbkma** [comment]
[Linux Mint](https://github.com/linuxmint/mint20.3-beta/issues/65#issuecomment-1004105246) apparently reverted c4a5e77 and 06292db. I have no idea if this really fixes the crashes.

**Comment by joakim-tjernlund** [comment]
I really don't get the ref/unrefing here:
https://github.com/mate-desktop/mate-panel/commit/06292db3c2b9a4ad81c7063c7bcff7cb6c0f927a

Why is there 2 unref of the same ptr?:
```
       window_wrapper = window;
...
	if (window_wrapper)
		g_object_unref (window_wrapper);
	g_object_unref (window);
```

**Comment by rbuj** [comment]
I recall that when you get the window wrapper, it always stores an extra reference internally to avoid creating new wrappers, and we need to get a clean wrapper to force new window thumbnails. See #1191

**Comment by muktupavels** [comment]
More or less double-free... `gdk_x11_window_foreign_new_for_display` is transfer full, you are supposed to call `g_object_unref` once.

**Comment by joakim-tjernlund** [comment]
What about ```gdk_x11_window_lookup_for_display```? only once there too?

**Comment by muktupavels** [comment]
No, it is transfer none, you are not supposed to unref returned value.

**Comment by joakim-tjernlund** [comment]
@rbuj , given the above, is it possible that:
```
	if (window_wrapper)
		g_object_unref (window_wrapper)
```
should be removed?

**Comment by rbuj** [comment]
I think you mean it should avoid any problems with lookup table.

gdk/x11/gdkwindow-x11.c
```
GdkWindow *
gdk_x11_window_foreign_new_for_display (GdkDisplay *display,
                                        Window      window)
{
...
  if ((win = gdk_x11_window_lookup_for_display (display, window)) != NULL) /* search in the lookup table */
    return g_object_ref (win);
...
  win = _gdk_display_create_window (display);
  win->impl = g_object_new (GDK_TYPE_WINDOW_IMPL_X11, NULL);
....
  g_object_ref (win);
  _gdk_x11_display_add_window (display, &GDK_WINDOW_XID (win), win); /* add in the lookup table */
....
  return win;
}
```
gdk/x11/gdkxid.c
```
void
_gdk_x11_display_add_window (GdkDisplay *display,
                             XID        *xid,
                             GdkWindow  *data)
{
  GdkX11Display *display_x11;

  g_return_if_fail (xid != NULL);
  g_return_if_fail (GDK_IS_DISPLAY (display));

  display_x11 = GDK_X11_DISPLAY (display);

  if (!display_x11->xid_ht)
    display_x11->xid_ht = g_hash_table_new ((GHashFunc) gdk_xid_hash,
                                            (GEqualFunc) gdk_xid_equal);

  if (g_hash_table_lookup (display_x11->xid_ht, xid))
    g_warning ("XID collision, trouble ahead");

  g_hash_table_insert (display_x11->xid_ht, xid, data);
}
```

**Comment by joakim-tjernlund** [comment]
I just meant that the  ref/unref is asymmetric
gdk_x11_window_foreign_new_for_display() will unref twice, one too many
while for gdk_x11_window_lookup_for_display() you do ref then unref so it is basically an NOP

**Comment by joakim-tjernlund** [comment]
Yes, that PR looks right, no more double unref. Added to my mate-panel-1.26.1 now.

**Comment by tofurky** [comment]
Also giving #1291 a try, I will report back if I experience additional crashes.

**Comment by joakim-tjernlund** [comment]
> Yes, that PR looks right, no more double unref. Added to my mate-panel-1.26.1 now.

Still working fine for me.

**Comment by lukefromdc** [comment]
While I do not get the crash, https://github.com/mate-desktop/mate-panel/pull/1291 didn't cause any problems for me on testing it

**Comment by joakim-tjernlund** [comment]
> @tofurky or any other here. Can you please confirm that PR fixes your problem?

No more crashes for me, works fine.

**Comment by tofurky** [comment]
> @tofurky or any other here. Can you please confirm that PR fixes your problem?

Yes, no crashes with PR.

**Comment by raveit65** [comment]
New release https://github.com/mate-desktop/mate-panel/releases/tag/v1.26.2

**Comment by davidhedlund** [comment]
![Screenshot at 2023-07-14 08-31-20](https://github.com/mate-desktop/mate-panel/assets/6416073/c05647b5-3e80-4435-804b-cc1ed2f934d3)

* Trisquel 11 (based on Ubuntu 22.04)
* mate-panel 1.26.2-1+11.0trisquel10
* libwnck-3-0 40.1-1
* mate-desktop 1.26.0-1

**Comment by davidhedlund** [comment]
@raveit65 Is my issue related to this bug?

**Comment by davidhedlund** [comment]
This issue referred to this one:
* https://github.com/mate-desktop/mate-applets/issues/612

**Comment by raveit65** [comment]
This bug was fixed with with 1.26.2 release as i mentioned before.
Please generate a stacktrace and open a new report.
