### ISSUE TITLE
GTK+ 3.22:  GLib-GObject-WARNING in .xsession-errors

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#359]
This warning turns up in .xsession-errors in a gtk3 mate session on Debian Unstable as of Oct 25, 2015: 

(mate-panel:1701): GLib-GObject-WARNING **: /build/glib2.0-l3js1a/glib2.0-2.46.1/./gobject/gsignal.c:2516: signal 'size_request' is invalid for instance '0x156cae0' of type 'GtkLabel'

Not seeing any obvious problems from this though
##

**Comment by raveit65** [comment]
size_request is deprecated, should be replaced with prefered_size.
sigh

**Comment by raveit65** [comment]
btw, looks like that debian unstable doesn't have the reverted commit in glib which was introduced with previous versions and spams logs and terminals.

**Comment by lukefromdc** [comment]
size_request turns up in 18 files in the source, but I was only able to find five of these
also including the word "label."  These are:

nothng.cP
clock.c
fish.c (not running)
fixedtip.c ( GtkWidget      *label;)
window-list.c

the fish applet is not in my panel, so it's not the source of the warning I am
seeing

**Comment by monsta** [comment]
As for now, I don't see any warnings about ```size_request``` in ```~/.xsession-errors``` (Debian Testing, GTK+3 build of MATE, GTK+ 3.18.7).
I guess this deprecation has been fixed since then?

**Comment by lukefromdc** [comment]
Still there with gtk3.19. Here's what I just found in .xsession-errors concerning mate-panel  with gtk3.19.10:

(mate-panel:4058): GLib-GObject-WARNING **: /build/glib2.0-2.46.2/./gobject/gsignal.c:2516: signal 'size_request' is invalid for instance '0x221ef70' of type 'GtkLabel'

(mate-panel:4058): Gtk-WARNING **: Negative content width -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkToggleButton)


(mate-panel:4058): Gtk-WARNING **: Negative content width -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkToggleButton)


(mate-panel:4058): Gtk-WARNING **: Negative content width -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkToggleButton)


(mate-panel:4381): GLib-GObject-WARNING **: /build/glib2.0-2.46.2/./gobject/gsignal.c:2516: signal 'size_request' is invalid for instance '0x102cf80' of type 'GtkLabel'
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

(mate-panel:4381): Gtk-WARNING **: Negative content width -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkToggleButton)

**Comment by monsta** [comment]
Ok, maybe it's those messages that are turned on only in development version of GTK+3...

**Comment by monsta** [comment]
@lukefromdc: how's it going now with 3.21? Because I don't see these warnings with 3.20...

**Comment by lukefromdc** [comment]
I still get things like 

(mate-panel:3782): GLib-GObject-WARNING **: gsignal.c:2517: signal 'size_request' is invalid for instance '0x227fc50' of type 'GtkLabel'

(mate-panel:3782): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate PanelWidget's child MatePanelAppletFrameDBus 0x20cc610. Allocation is 1x24, but minimum required size is 0x48.

(mate-panel:3782): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate MatePanelAppletFrameDBus's child MatePanelAppletContainer 0x1e42720. Allocation is 1x24, but minimum required size is 0x48.

(mate-panel:3782): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate MatePanelAppletContainer's child GtkSocket 0x20ba450. Allocation is 1x24, but minimum required size is 0x48.

**Comment by monsta** [comment]
So the old warnings seem to be gone, but the new ones have appeared...

**Comment by lukefromdc** [comment]
Right now the window-list applet is the worst offender, absoutely spamming system logs with this sort of message in GTK 3.21 and as above in this issue also appear in GTK 3.20:

`gtk_widget_size_allocate(): attempt to underallocate MatePanelApplet's child WnckTasklist 0xe36240. Allocation is 391x26, but minimum required size is 585x26.`

I've done some preliminary digging but at the moment have not been able to find the source of this nor a fix

**Comment by Safari77** [comment]
I had configured a bigger font for clock-applet in ```~/.config/gtk-3.0/gtk.css``` , but had the panel size at 32. I had to manually up it to 38 to prevent five spam lines a second to journal:
```journal: gtk_widget_size_allocate(): attempt to underallocate MatePanelApplet's child GtkToggleButton 0x55b0dd4462d0. Allocation is 290x32, but minimum required size is 290x33.```

Additionally, 124 spam lines to journal by wnck each time I switch workspace. gtk 3.22.0.

**Comment by lukefromdc** [comment]
Plus more spam from wnck-applet window list every time a window is
opened-I think it's another 5 lines.

**Comment by lukefromdc** [comment]
GTK 3.22.1 just came out-and includes suppression of all those underallocation lines. That will greatly help with the log spam issue while presumably gtk options at startup can be used for deliberate debugging. Building GTK 3.22.1 now and will test as soon as installed

**Comment by lukefromdc** [comment]
Confirmed: the underallocation spam is gone

**Comment by monsta** [comment]
Ok, anything left with current 3.22.x?

**Comment by raveit65** [comment]
I have an report about this with f25 https://bugzilla.redhat.com/show_bug.cgi?id=1398414
Can we back port some fixes to 1.16 ?

**Comment by monsta** [comment]
First we need to check current situation with 1.17...

**Comment by lukefromdc** [comment]
When I checked .xsession-errors with currtent 1.17 and GTK 3.22 mate-panel came up as "not found" in a Pluma search.  On restarting the panel with syslog on display I got only these warnings from applets not part of the mate-panel package:
```

Nov 25 14:45:33 ubuntu mate-cpufreq-ap[20093]: gtk_orientable_get_orientation: assertion 'GTK_IS_ORIENTABLE (orientable)' failed
Nov 25 14:45:33 ubuntu mate-cpufreq-ap[20093]: gtk_orientable_get_orientation: assertion 'GTK_IS_ORIENTABLE (orientable)' failed
Nov 25 14:45:33 ubuntu mate-inhibit-ap[20089]: gsignal.c:2523: signal 'expose-event' is invalid for instance '0x5595279d81d0' of type 'GpmInhibitApplet'
Nov 25 14:45:33 ubuntu mate-inhibit-ap[20089]: gsignal.c:2523: signal 'expose-event' is invalid for instance '0x5595279d81d0' of type 'GpmInhibitApplet'
Nov 25 14:45:34 ubuntu trashapplet[20099]: Allocating size to GtkImage 0x55b70a73b140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Nov 25 14:45:34 ubuntu trashapplet[20099]: Allocating size to GtkImage 0x55b70a73b140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Nov 25 14:45:34 ubuntu trashapplet[20099]: Allocating size to GtkImage 0x55b70a73b140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Nov 25 14:45:34 ubuntu trashapplet[20099]: Allocating size to GtkImage 0x55b70a73b140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Nov 25 14:45:34 ubuntu clock-applet[20097]: gsignal.c:2523: signal 'size_request' is invalid for instance '0x55720eb04df0' of type 'GtkLabel'
Nov 25 14:45:34 ubuntu clock-applet[20097]: gsignal.c:2523: signal 'size_request' is invalid for instance '0x55720eb04df0' of type 'GtkLabel'
```

Note that Ubuntu is just a machine name picked for being common when I used to run Ubuntu. This is a defense against  machine names being logged by wifi access points and being usable by an adversary. I am now using Debian Unstable, not Ubuntu

**Comment by raveit65** [comment]
I hope you guys agree with me to remove this report from gtk+-3 milestone, as most warnings are gone and only a few are left in my .xsession-errors.
If not,.....add this milestone again :-)

**Comment by lukefromdc** [comment]
Fine by my

**Comment by monsta** [comment]
Ok for me too. BTW, `size_request` warning in clock should've been fixed by https://github.com/mate-desktop/mate-panel/commit/02b7511302cef8b527cbc45c1ac674ab28f2dc01. Other warnings mentioned above are in mate-applets. So maybe we could close this?

**Comment by raveit65** [comment]
I have only 2 left in log
```
(mate-panel:18434): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(mate-panel:18434): Gtk-WARNING **: Allocating size to PanelToplevel 0x558e3ed523f0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

**Comment by lukefromdc** [comment]
I have no instances of "panel" whatsoever in xsession-errors or in syslog, these size warnings can be theme-dependent though

**Comment by raveit65** [comment]
I am i doubt that those warnings are theme related, because i get theme with your Ubuntu-Legacy and adwaita theme too. ;-)
But , as i can't fix them for myself i agree with closing.

**Comment by raveit65** [comment]
for the record,upstream report about
https://bugzilla.redhat.com/show_bug.cgi?id=1398414

**Comment by monsta** [comment]
Hmm I don't see that warning about PanelToplevel allocation...
