### ISSUE TITLE
GTK3 Panels do not resize to fit display when rotated using xrandr

### ISSUE THREAD

**Issue by wyatt8740** [mate-desktop/mate-panel#552]
After rotating my display via `xrandr --output LVDS1 --rotate left`, my MATE panel bars stick off the edge of the visible screen. The only way to make them fit inside the screen is to restart mate-panel manually.

I think this worked when building mate-panel based on GTK2.

I am using Debian's Mate Desktop 1.16.1 in Debian Sid.

Normal landscape view:
![Normal landscape view](http://i.imgur.com/CpsgCFJ.png)

After rotation:
![After rotation](http://i.imgur.com/wRVLJvw.png)

After rotating and running `killall mate-panel`:
![After rotating and running 'killall mate-panel'](http://i.imgur.com/CMGAD5n.png)

One other thing that might just be due to my theme, but I can't seem to make the 'hide' buttons narrower than in the screenshot. They were about half as wide in GTK2. I am guessing there's some CSS I could use that I am not currently aware of?

**Comment by raveit65** [comment]
This fixes the hide buttons.
https://github.com/mate-desktop/mate-themes/commit/11f70c602cac40eb58e372e11f67194243302dbb

**Comment by monsta** [comment]
I think I see the same issue when I move panel from horizontal to vertical (e.g. from bottom to left) via panel prefs dialog...

**Comment by wyatt8740** [comment]
@raveit65 That doesn't really fix the hide buttons. I was referring to how wide they are compared to what I'm used to. Your patch just makes them look darker.

Of course, until recently I was using a modified version of the Ubuntu Lucid theme, but I can't seem to make the background color for the toolbars change either. This impacted the size of the hide buttons there too.

**Comment by raveit65** [comment]
Nope, i don't know what you see, but this is how they should look for mate-themes.

**Comment by wyatt8740** [comment]
Hm, OK.

Still, rotation is broken.

**Comment by lukefromdc** [comment]
Any time something like this is applied only on restarting the panel, you are looking at something not being redrawn when it should have been. This seems to have gotten worse with the last three GTK3 cycles.

**Comment by wyatt8740** [comment]
@lukefromdc so is this GTK3's fault? Or something we can fix on the MATE end?

**Comment by lukefromdc** [comment]
All of the other such issues had to be fixed or worked around on our end

**Comment by monsta** [comment]
Ok, this is now fixed in https://github.com/mate-desktop/mate-panel/commit/93f73619bbd76dce14c3b2df9756ad59136b8223. I'll check if I can backport it to 1.16 branch as well.

**Comment by monsta** [comment]
Fixed for GTK+3 build of 1.16 in https://github.com/mate-desktop/mate-panel/commit/e15c121f7703b2fe328753fe6be4cc59001b036e (GTK+2 build already works fine, so no changes needed there).

**Comment by wyatt8740** [comment]
Thanks! @monsta I still have one question while you're here. Is there a nice script to automatically fetch and attempt to build the entire desktop environment? Last time I compiled mate manually it was a huge pain, and I'm considering doing it to move back to GTK2 for a little while longer.

**Comment by lukefromdc** [comment]
MATE 1.16 is the last version that can be built with GTK2. GTK2 support is gone as of 1.18

**Comment by wyatt8740** [comment]
@lukefromdc I am running 1.16. What is the configuration option?

**Comment by lukefromdc** [comment]
--with-gtk=3.0 or --with-gtk=2.0 and default was gtk2 right up until packages became GTK3 only. A few packages are GTK3 only even in 1.16 BTW

**Comment by wyatt8740** [comment]
OK, thanks a bunch!

I won't be staying on GTK2 much longer, anyway, but it's much appreciated; Debian has only packaged GTK3 for a while now (and I have to make custom builds of GTK3 to fix some annoyances in its file chooser already).

**Comment by monsta** [comment]
I use [debian-packages](https://github.com/mate-desktop/debian-packages) repo for building .deb packages in my Debian/Ubuntu/Mint systems. You can use 1.16 branch to build 1.16 packages (and GTK+2 is the default there, unlike in Debian archives).

We also released mate-panel 1.16.2 which has the fix for this bug.

**Comment by MartinX3** [comment]
Using Ubuntu Mate x64 17.04 with Mate-Panel Version 1.18.1-0ubuntu2.

This Problem still happen.

Please Reopen this Issue.

**Comment by cykerway** [comment]
not sure if it's the same bug, but if you have dual monitors you need to rotate both outputs for the panels to appear at the right position;

**Comment by wyatt8740** [comment]
@cykerway it's not the same problem, and this bug is old and dead. You might want to file a new one.
