### ISSUE TITLE
Wrong behavior for drawer applet

### ISSUE THREAD

**Issue by edomato** [mate-desktop/mate-panel#556]
![drawer](https://cloud.githubusercontent.com/assets/1550373/24839089/e0da0988-1d2a-11e7-8a89-4e08074af8f3.gif)

As you can see in the animated gif, when you open a drawer and close it, if you move the cursor in and out of the panel, the icon for the drawer changes to the first application in it when it you always display the drawer icon.

**Comment by lukefromdc** [comment]
What version of mate-applets and mate-panel, is this GTK2 or GTK3, and if GTK 3 which version. Also over what distro? I can't duplicate this on Debian Unstable with GTK 3.22.11 and MATE 1.19 compiled locally from git master

**Comment by edomato** [comment]
Ok, sorry for the lack of information :-(

The distribution is also Debian Unstable with the latest packages from that repository.

mate-applets 1.16.0-1
mate-panel 1.16.0-2
libgtk-3-0:amd64 3.22.11-1

**Comment by DavideRossi** [comment]
I have the same behavior with Mint's latest version (18.2).
Not only the icon displayed is that of the first application but, at times, if you click in the drawer area the first application is started (and the drawer is not opened).

mate-applets 1.18.1-1
mate-panel 1.18.3-2
libgtk-3-0 3.18.9

**Comment by MobiusTesseract** [comment]
Just went from Linux Mint 18.1 to 18.2, don't know what my previous versions were, but now I am on:
mate-applets 1.18.1-1+sonya
mate-panel 1.18.3-2+sonya
libgtk-3-0 3.18.9-1ubuntu3.3

I have the drawer on the bottom panel and never had a problem before, it just appeared. Since for a bottom mounted panel the first element of the drawer is the close button (instead of last) that is what appears instead and mine is big (since the drawer is wide the way I use it) and covers other elements as well. Unfortunately this is a deal-breaking bug for me if it's going to hide what is around it...

![image](https://user-images.githubusercontent.com/6500579/28324474-24fd30a6-6be4-11e7-8f06-192f1afdf10c.png)
![image](https://user-images.githubusercontent.com/6500579/28324555-61ee7c2c-6be4-11e7-8c5d-d0d106d8df2d.png)

**Comment by mp107** [comment]
Went from Linux Mint MATE 18.1 to 18.2 and the issue came up also for me.

GIF:
![GIF](http://obrazki.elektroda.pl/8334091300_1501599408.gif)

Video (YouTube):
[![Alt text for your video](https://img.youtube.com/vi/VVRyYpuiOZ8/0.jpg)](http://www.youtube.com/watch?v=VVRyYpuiOZ8)

**Comment by morfeus2** [comment]
Same annoying behavior confirmed also in Debian Stretch.

1.16.0-1 mate-applets
1.16.0-1 mate-applets-common
1.16.0-1 mate-backgrounds
1.16.1-1 mate-control-center
1.16.1-1 mate-control-center-common
1.16.2-2 mate-desktop
1.16.2-2 mate-desktop-common
1.16.0+1 mate-desktop-environment
1.16.0+1 mate-desktop-environment-core
1.16.2-1 mate-icon-theme
1.16.0+dfsg1-2 mate-icon-theme-faenza
1.16.0-1 mate-media
1.16.0-1 mate-media-common
1.16.0-2 mate-menus
1.16.1-1 mate-notification-daemon
1.16.1-1 mate-notification-daemon-common
1.16.2-1 mate-panel
1.16.2-1 mate-panel-common
1.16.0-2 mate-polkit:amd64
1.16.0-2 mate-polkit-common
1.16.2-1 mate-power-manager
1.16.2-1 mate-power-manager-common
1.16.1-1 mate-screensaver
1.16.1-1 mate-screensaver-common
1.16.1-1 mate-session-manager
1.16.2-1 mate-settings-daemon
1.16.2-1 mate-settings-daemon-common
1.16.0-2 mate-system-monitor
1.16.0-2 mate-system-monitor-common
1.16.3-1 mate-terminal
1.16.3-1 mate-terminal-common
3.22.11-1 mate-themes
1.16.0-1 mate-user-guide
1.16.0-1 mate-utils
1.16.0-1 mate-utils-common

**Comment by adam-funk** [comment]
I've had the same problem since installing Ubuntu-MATE 17.04 in the summer.  Sometimes the drawer icon doesn't change, and clicking it launches the first program in the drawer instead of opening the drawer.  Is there a workaround?

mate-applets                            1.18.1-0ubuntu1
mate-panel                              1.18.1-0ubuntu2
libgtk-3-0:amd64                        3.22.11-0ubuntu3

**Comment by ivazqueznet** [comment]
Can confirm that I have seen this same problem in both Fedora 25 upgraded from an earlier version and in a fresh install of Fedora 26.

mate-panel-1.18.4-1.fc25.x86_64
mate-panel-libs-1.18.4-1.fc25.x86_64

mate-panel-1.18.4-1.fc26.x86_64
mate-panel-libs-1.18.4-1.fc26.x86_64

**Comment by mwrsa** [comment]
I have this issue as well. For me it started when I updated to Mint 18.2 Sonya and Mate from 1.16* to 1.18*. Now I have three devices with all Mint 64bit and up do date on updates:

#1 Mint 18.1: No issues.
#2 Mint 18.2 from Mint 18.1: Issue as described
#3 Mint 18.2 fresh install: Initially same issue, but disappeared after some time, no issue since.

Great right? Any solutions yet?

**Comment by mwrsa** [comment]
This issue is persisting in Mint 18.3
I am actually severely disappointed that this crap hasn't been fixed in almost 10 months. There is no progress visible in this issue report either. Just had to bring it up again.

**Comment by edomato** [comment]
I didn't have time to test it yet, but the first reply to this issue says
that in 1.19 this behavior seems to not be present.

So, maybe it's fixed in the next version and I would be able to confirm it
when I have time to make the tests.

**Comment by lukefromdc** [comment]
I just retested this in mate-panel 1.19.3 git master current through 12-30-2017(last commit to master as this is posted) and indeed the issue seems fixed.

**Comment by pstef** [comment]
So which commit fixed this?

**Comment by lukefromdc** [comment]
I have no idea at all, as I don't recall any commits deliberately aimed at fixing this. You could always bisect for it, assuming a change in GTK, glib etc didn't fix it.

**Comment by mwrsa** [comment]
OK, in that case - sorry for the misunderstanding. "cannot reproduce" was not equal to "doesn't exist" to me...
So, since at least one is a work system here, I have to wait for an official and tested update, or rather distribution upgrade.
Thank you for testing and clarification!

**Comment by edomato** [comment]
Hi, today I updated my Debian box that pulls from unstable and Mate was upgraded to 1.20.0 since it was uploaded yesterday to Debian repositories.

This issue still persist on it (I even tried with a new user with no previous configuration) so at least the compilation on Debian still has this bug (and probably will every distribution based on it).

So, does anyone can give some direction on how we can help to finally chase this bug? (maybe is a problem with another library that Mate depends on)

@lukefromdc have you made the test on Debian?, maybe you can check with the Debian mantainers for Mate what are the differences between your compilation and those of the mantainers?

@flexiondotorg should this issue stay closed?, should I open a new issue with the same problem?

Thanks for all.

**Comment by info-cppsp** [comment]
#734 should fix this.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-panel/commit/b08bc130853b2f737eb47113357513f5e937eb47
squashed and merged https://github.com/mate-desktop/mate-panel/pull/734 and the issue is all the way gone in my testing

**Comment by mwrsa** [comment]
Ok then, please provide step by step instructions to fix said issue on my work system (still on mate 1.18), thank you!

**Comment by edomato** [comment]
Ok, hope that the Debian version get this quickly and fix the problem too soon 😄

**Comment by lukefromdc** [comment]
You could build mate-panel from git master source and install it. You will need the development packages for those things the configure.ac script looks for, which are the <something>-dev packages on Ubuntu based distros

**Comment by info-cppsp** [comment]
just install gtk+ 3.22 and glib 2.50 first...
it may be best if you just wait for mint 19...

[mate-panel tmpmaster 2018-02-15.pdf](https://github.com/mate-desktop/mate-panel/files/1729220/mate-panel.tmpmaster.2018-02-15.pdf)
If you want, this is a renamed .zip file with my temp master, before the 1.20 release.
you have to install some packages like
https://github.com/mate-desktop/mate-panel/pull/718#issuecomment-361894860
then the usual
```
./autogen.sh --prefix=/usr
make
sudo make install
```
I'll update the readme, when I get to it...

**Comment by ivazqueznet** [comment]
Confirmed that part 4 of #734 alone fixes this, and that it patches cleanly and builds against 1.18.6 as well (for Fedora 26).
